[package]
name = "liquidity-book"
version.workspace = true
edition.workspace = true

[dependencies]
anchor-gen = { workspace = true }
anchor-lang = { workspace = true }
solana-sdk = { workspace = true }
rand = "0.8.5"
