[package]
name = "saros-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
anchor-lang = { workspace = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-program-pack = { workspace = true }
solana-pubkey = { workspace = true }
thiserror = { workspace = true }
arrayref = { workspace = true }
anyhow = { workspace = true }
spl-token-2022-interface = { workspace = true }
spl-token-interface = { workspace = true }
ruint = { workspace = true }
itertools = { workspace = true }

liquidity-book = { workspace = true }
rewarder-hook = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
